### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by danielpronych**
Submit fix to a minor spelling error in the README file.

### CODE REVIEW

**Comment by tcyrus** [comment]
:+1:

**Comment by Mauron** [comment]
Isn't the README written in US English?

**Comment by PaluMacil** [comment]
:+1: looks good! Let's do it! :)

**Comment by sjoqvist** [comment]
> Isn't the README written in US English?

@Mauron I think it is, but does it make a difference? ["Compromized" is a misspelling](https://en.wiktionary.org/wiki/compromize) in US English as well, isn't it?

One can argue that this pull requests overlooks other mistakes (the ones I spot are "managment", "relavent" in two places, and "run" instead of "Run" in two places). But I don't think that one pull request needs to solve everything.

**Comment by getsadzeg** [comment]
@Mauron It's "compromised" anyway.

**Comment by Mauron** [comment]
My bad.

**Comment by justinmeza** [comment]
Good catch 👍  spelling is hard >____<

**Pull request merged**
